### ISSUE TITLE
The input fields do not change while copy pasting an OTP

### ISSUE THREAD

**Issue by dewanshrawat15** [devfolioco/react-otp-input#121]
- **Steps to reproduce the issue**:
- Copy a 3 - 4 digit number.
- Visit the [React OTP Input website](https://devfolioco.github.io/react-otp-input/)
- Paste the 3 - 4 digit number.
- The focus would still be on the first field, whereas it should change to the latest updated field.

- **Relevant error messages and/or screenshots**:
![Screenshot 2020-10-01 at 11 44 55 AM](https://user-images.githubusercontent.com/17003127/94774434-8a6c3300-03db-11eb-8589-3e3c61f277b2.png)

**Comment by karkranikhil** [comment]
Let me fix this

**Comment by dewanshrawat15** [comment]
@karkranikhil already did. Please refer #123

**Comment by apollonian** [comment]
The issue has been fixed with [v2.3.0](https://github.com/devfolioco/react-otp-input/releases/tag/v2.3.0)!

**Comment by antondev22** [comment]
@apollonian 
I checked v2.3.0 but the autoComplete issue is still not resolved.

![image](https://user-images.githubusercontent.com/88622133/183942604-64707c3f-5c6f-40ab-8b4e-fe65d846a580.png)

![image](https://user-images.githubusercontent.com/88622133/183942717-d5fe1852-987f-40d9-ad60-14b966f94e22.png)

I couldn't find the autoComplete props.
