### ISSUE TITLE
isInputNum accepting "+,-,e" and back space is not working when this characters entered

### ISSUE THREAD

**Issue by shivaMohan1995** [devfolioco/react-otp-input#29]
When  isInputNum  is used the input accepts `+`, `-`, `e` and when they are entered `backspace` doesn't clear the input.

**Comment by joao-arvins** [comment]
This PR should fix the issue: https://github.com/devfolioco/react-otp-input/pull/30

**Comment by Praneeth543** [comment]
is this issue solved and merged in the latest version?

**Comment by RahulShahUI** [comment]
this issue is still there. can we have any solution or suggestions for other module?
