### ISSUE TITLE
Some tailwind styling like width is not working

### ISSUE THREAD

**Issue by void-hr** [devfolioco/react-otp-input#414]
version of react-otp-input : ^3.0.4
Tailwind CSS width property is not working.

**Comment by prateek3255** [comment]
Can you please add a snippet or a sandbox to show a reproducible example?

**Comment by void-hr** [comment]
Below is snippet of package json
![Image]https://github.com/devfolioco/react-otp-input/assets/89070559/4afd4aaf-b8ea-41b7-9ef8-913df888d49a)

Code h-12 is working but w-12 is not working
![image](https://github.com/devfolioco/react-otp-input/assets/89070559/e54f8ac5-2b6e-4b98-aa0c-a6af2fc73f01)

Output @localhost:3000
![image](https://github.com/devfolioco/react-otp-input/assets/89070559/6065705c-7f8d-49bd-8b28-66c3d46230d7)

**Comment by prateek3255** [comment]
@void-hr The code you shared looks fine, and I think the styles you added for the input are getting passed to the relevant inputs as well, which you can check by inspecting the input elements. If you still face any issues, do share a reproducible codesandbox so that we can debug it.

**Comment by void-hr** [comment]
@prateek3255 I am pasting the link of codesandbox, let me know in case you need anything
[CODESANDBOX](https://codesandbox.io/s/little-worker-wrcf94?file=/src/App.js)

**Comment by void-hr** [comment]
@prateek3255 I was exploring a little bit, correct me if I am wrong maybe this issue is arising because width is assigned 1 rem as constant by default?

      style: Object.assign(
                { width: '1em', textAlign: 'center' } as const,
                isStyleObject(inputStyle) && inputStyle
              ),

**Comment by prateek3255** [comment]
Yeah I believe you are right, these styles exist for legacy reasons. I think we can expose a prop to not apply these styles for now, and then it can be removed with the next major version. Would you like to work on it @void-hr ?

**Comment by void-hr** [comment]
@prateek3255 Yeah Sure! I want to give it a try one more thing I want to mention is one can assign width with !important modifier than it will work.

**Comment by prateek3255** [comment]
Yeah ideally you shouldn't need to do that

**Comment by void-hr** [comment]
@prateek3255 can you suggest me some ways in which I can see visual changes while playing with code to get more idea of what particular changes are taking place.

**Comment by prateek3255** [comment]
Yeah you can run the example vite example which will show you live changes, as you make changes to the library code:
https://github.com/devfolioco/react-otp-input#to-run-the-vite-example

**Comment by prateek3255** [comment]
This was fixed with v3.1.0

**Comment by ayush-sd** [comment]
This is not fixed, I am still facing this issue, `width: 1rem` is set on the element styles...
Version: `3.1.0`
<img width="524" alt="image" src="https://github.com/devfolioco/react-otp-input/assets/134925941/67fb793e-fc97-4708-b320-0b4b8b4feec9">

**Comment by abena07** [comment]
thanks this helped me! 🙏🏿
